name: Deploy Privacy Policy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'PRIVACY_POLICY.md'
      - 'doc/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Siapkan Dokumen
        run: |
          mkdir -p _site
          if [ -f "PRIVACY_POLICY.md" ]; then
            cp PRIVACY_POLICY.md _site/index.md
          else
            echo "# Privacy Policy" > _site/index.md
          fi

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifacts Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy ke Pages
        id: deployment
        uses: actions/deploy-pages@v4
